### ISSUE TITLE
The `Ops` definition in Rust is different from the definition in JavaScript.

### ISSUE THREAD

**Issue by NO-MAP** [AnubhabB/diff-match-patch-rs#5]
JavaScript: [link](https://github.com/JackuB/diff-match-patch/blob/b51e1044a688503d3c299a7b14a6eaf9d59c75d3/index.js#L65)
```javascript
var DIFF_DELETE = -1;
var DIFF_INSERT = 1;
var DIFF_EQUAL = 0;
```

Rust:
```rust [link](https://github.com/AnubhabB/diff-match-patch-rs/blob/7952db70c788ec639633194b3c91074423b8a5f1/src/dmp.rs#L18
)
pub enum Ops {
    Delete = -1,
    Insert,
    Equal,
}
```

I'm not sure which one is the standard design.

**Comment by AnubhabB** [comment]
Well as far as I understand it's different for all implementations I've seen, basically everyone relies on strengths of the language! For languages that didn't support `enum` as a data structure the implementations would go ahead with constants.

Are you trying to use the raw diff blocks across libraries/ implementations? If you could share the problem/ use-case we could have a quick discussion/ implementation around it.

Cheers
